import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'models.dart';

/// Builds a one-to-two page summary the user can show or send to their doctor.
Future<void> shareDoctorBrief(ReportAnalysis a, String profileName) async {
  // Standard PDF fonts only cover Latin text. Try Noto Sans so other scripts
  // render too; fall back to the built-in font when offline.
  pw.ThemeData? theme;
  try {
    theme = pw.ThemeData.withFont(
      base: await PdfGoogleFonts.notoSansRegular(),
      bold: await PdfGoogleFonts.notoSansBold(),
    );
  } catch (_) {
    theme = null;
  }

  final doc = pw.Document(theme: theme);
  final flagged = a.values
      .where((v) => v.flag == 'low' || v.flag == 'high')
      .toList();

  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      build: (context) => [
        pw.Text(
          'Health summary for $profileName',
          style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          '${a.reportType}${a.reportDate == null ? '' : ' · ${a.reportDate}'}',
        ),
        pw.SizedBox(height: 16),
        if (a.urgent)
          pw.Container(
            padding: const pw.EdgeInsets.all(8),
            margin: const pw.EdgeInsets.only(bottom: 12),
            color: PdfColors.red100,
            child: pw.Text('Needs prompt attention. ${a.urgentReason ?? ''}'),
          ),
        pw.Text(
          'Summary',
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 4),
        pw.Text(a.summary),
        pw.SizedBox(height: 16),
        if (flagged.isNotEmpty) ...[
          pw.Text(
            'Results outside the usual range',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          for (final v in flagged)
            pw.Bullet(
              text:
                  '${v.name}: ${v.valueText}${v.unit == null ? '' : ' ${v.unit}'} '
                  '(${v.flag}${v.referenceText.isEmpty ? '' : ', usual ${v.referenceText}'})',
            ),
          pw.SizedBox(height: 16),
        ],
        pw.Text(
          'All results',
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 4),
        pw.TableHelper.fromTextArray(
          headers: ['Test', 'Result', 'Usual range', 'Flag'],
          data: [
            for (final v in a.values)
              [
                v.name,
                '${v.valueText}${v.unit == null ? '' : ' ${v.unit}'}',
                v.referenceText,
                v.flag,
              ],
          ],
          headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          cellAlignment: pw.Alignment.centerLeft,
        ),
        if (a.questionsForDoctor.isNotEmpty) ...[
          pw.SizedBox(height: 16),
          pw.Text(
            'Questions to ask',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          for (final q in a.questionsForDoctor) pw.Bullet(text: q),
        ],
        pw.SizedBox(height: 24),
        pw.Text(
          'Generated by HealthVault from the lab report. This is a summary for '
          'discussion, not medical advice. Check values against the original report.',
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
        ),
      ],
    ),
  );

  await Printing.sharePdf(
    bytes: await doc.save(),
    filename: 'health-summary.pdf',
  );
}
